[misc]
only = ["flatpak", "distrobox", "brew_formula"]
ignore_failures = ["flatpak", "distrobox", "brew_formula"]
skip_notify = true
assume_yes = true
no_retry = true
no_self_update = true

[distrobox]
use_root = false

[flatpak]
use_sudo = false
